# --- General & Path Configuration ---
seed: 'sf_1'
base_dir: '/home/hep/lr1424/1P1Qm_fork/'
save_dir: '/home/hep/lr1424/1P1Qm_fork/saved_models/'
data_dir: '/home/hep/lr1424/1P1Qm_fork/'
dump: '/home/hep/lr1424/1P1Qm_fork/dumps/' # Inference results
resume: false # Set to true to resume from the latest checkpoint in save_dir/seed
desc: 'TensorFlow-based training run'
save: true # Save model checkpoints during training

# --- Dataset & Preprocessing ---
dataset: 'jetclass'
train_n: 2000   # Max number of training samples
valid_n: 400    # Max number of validation samples
batch_size: 32  # Batch size for training and validation
norm_pt: false  # Normalize pT by 1/jet_pt
flat: false     # Use flat m_jj distribution for training data
patience: 2

# --- Model Architecture ---
wires: 4
cutoff_dimension: 5 # cutoff_dimension
num_layers: 1
params_per_wire: 3
circuit_type: 'normal'

# --- Training Hyperparameters ---
extra_weights: 16
epochs: 25
lr: 0.01
improv: 0.01
loss: 'MSE' # 'MSE' for MeanSquaredError or 'BCE' for BinaryCrossentropy

# --- Logging ---
log_wandb: false